### ISSUE TITLE
Will the examples be available on git?

### ISSUE THREAD

**Issue by oliverweissl** [perlinm/qLDPC#1]
I saw the mention of examples in a test py file. However there doesnt seem to be such file.

Will it be added?

**Comment by perlinm** [comment]
Thank you for your interest!

This is repo is currently only a "preview" for software that I have on a private company repo :slightly_smiling_face:.  I am still waiting to get approval from my company to release this software publicly.  That is unfortunately taking a while because I got caught at a bad time: our legal department is currently revising our internal open-source release policy.  I gave them a hard deadline of January (since I will be presenting this at [QIP 2024](https://qip2024.tw/)).  Keep your eyes peeled for updates!

**Comment by perlinm** [comment]
The codes are now public!  See https://github.com/Infleqtion/qLDPC

**Comment by perlinm** [comment]
@oliverweissl if you have questions or suggestions, let's continue the conversation in the new main repo.  I'll close this issue here.
